stages:
- cleanup
cleanup:
  stage: cleanup
  image:
    name: amazon/aws-cli:latest
    entrypoint: [""]
  script:
    - pwd
    - ls
    - cd /builds/upskillondevops/docker-awsecr/IaaC/AWS/scripts
    - pwd
    - echo "executing S3 content and bucket script"
    - chmod +x delete-s3-object.sh
    - ./delete-s3-object.sh
    - ls
    - echo "executing cft deletion script"
    - chmod +x delete-cft.sh
    - ./delete-cft.sh
    - ls
